# Generated by Django 5.1.2 on 2024-11-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='background_music',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
