# Generated by Django 5.1.2 on 2024-11-11 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0007_remove_worker_id_worker_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='first_name',
            new_name='cader',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='background_music',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.CharField(default='Ama', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='sap',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
