# Generated by Django 5.1.2 on 2024-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0008_rename_first_name_worker_cader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='picture',
            field=models.ImageField(default='static/images/male.webp', upload_to='workers/'),
        ),
    ]
