# Generated by Django 5.1.2 on 2024-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0009_alter_worker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='picture',
            field=models.ImageField(null=True, upload_to='workers/'),
        ),
    ]
